name: Lint and Test Automation

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  
      - name: Run PowerShell Script Analyzer
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: scripts/
